ALTER TABLE users ADD COLUMN IF NOT EXISTS auth0_sub VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';

ALTER TABLE therapists ADD COLUMN IF NOT EXISTS auth0_sub VARCHAR(255) UNIQUE;

ALTER TABLE admins ADD COLUMN IF NOT EXISTS auth0_sub VARCHAR(255) UNIQUE;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_users_auth0_sub ON users(auth0_sub);
CREATE INDEX IF NOT EXISTS idx_therapists_auth0_sub ON therapists(auth0_sub);
CREATE INDEX IF NOT EXISTS idx_admins_auth0_sub ON admins(auth0_sub);
