const PDFDocument = require('pdfkit');
const path = require('node:path');

const regularFontPath = path.join(__dirname, '../assets/fonts/dejavu/DejaVuSans.ttf');
const boldFontPath = path.join(__dirname, '../assets/fonts/dejavu/DejaVuSans-Bold.ttf');

const palette = {
  ink: '#3F332C',
  muted: '#6F6259',
  accent: '#8C4F3A',
  sand: '#E7D9CB',
  paper: '#FAF7F2',
};

const formatDate = (value, { timezone = 'UTC', includeTime = true } = {}) => {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'Not available';
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: timezone,
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    ...(includeTime ? { hour: 'numeric', minute: '2-digit', timeZoneName: 'short' } : {}),
  }).format(date);
};

const formatMoney = (amountMinor, currency) => {
  try {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: currency || 'INR',
    }).format(Number(amountMinor || 0) / 100);
  } catch {
    return `${currency || 'INR'} ${(Number(amountMinor || 0) / 100).toFixed(2)}`;
  }
};

const addRow = (doc, label, value) => {
  const top = doc.y;
  doc.font('ShuraSans').fontSize(9).fillColor(palette.muted).text(label, 54, top, { width: 170 });
  doc.font('ShuraSansBold').fontSize(10).fillColor(palette.ink).text(String(value || 'Not available'), 225, top, {
    width: 315,
    align: 'right',
  });
  doc.y = Math.max(doc.y, top + 23);
  doc.moveTo(54, doc.y).lineTo(540, doc.y).strokeColor(palette.sand).lineWidth(0.5).stroke();
  doc.moveDown(0.65);
};

const generateReceiptPdf = (receipt) => new Promise((resolve, reject) => {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 54,
    compress: false,
    info: {
      Title: `Shura receipt ${receipt.reference}`,
      Author: 'Shura',
      Subject: 'Client payment receipt',
    },
  });
  const chunks = [];
  doc.on('data', (chunk) => chunks.push(chunk));
  doc.on('error', reject);
  doc.on('end', () => resolve(Buffer.concat(chunks)));
  doc.registerFont('ShuraSans', regularFontPath);
  doc.registerFont('ShuraSansBold', boldFontPath);

  doc.rect(0, 0, doc.page.width, 142).fill(palette.paper);
  doc.font('ShuraSansBold').fontSize(28).fillColor(palette.accent).text('SHURA', 54, 48);
  doc.font('ShuraSans').fontSize(11).fillColor(palette.muted).text('Faith-centered mental health support', 54, 83);
  doc.font('ShuraSansBold').fontSize(20).fillColor(palette.ink).text('Payment receipt', 350, 52, {
    width: 190,
    align: 'right',
  });
  doc.font('ShuraSans').fontSize(9).fillColor(palette.muted).text(receipt.reference, 350, 82, {
    width: 190,
    align: 'right',
  });

  doc.y = 172;
  addRow(doc, 'Transaction reference', receipt.reference);
  addRow(doc, 'Amount', formatMoney(receipt.amountMinor, receipt.currency));
  addRow(doc, 'Payment status', receipt.statusLabel);
  addRow(doc, 'Transaction date', formatDate(receipt.transactionDate));

  if (receipt.refundStatusLabel) {
    addRow(doc, 'Refund status', receipt.refundStatusLabel);
  }
  if (Number(receipt.refundAmountMinor) > 0) {
    addRow(doc, 'Refund amount', formatMoney(receipt.refundAmountMinor, receipt.currency));
  }

  doc.moveDown(0.8);
  doc.font('ShuraSansBold').fontSize(13).fillColor(palette.ink).text('Appointment');
  doc.moveDown(0.7);
  addRow(doc, 'Therapist', receipt.therapistName || 'Not available');
  addRow(doc, 'Session date', receipt.scheduledAt
    ? formatDate(receipt.scheduledAt, { timezone: receipt.clientTimezone || 'UTC' })
    : 'Booking was not finalized');
  addRow(doc, 'Session type', receipt.sessionTypeLabel || 'Not available');
  addRow(doc, 'Duration', receipt.durationMinutes ? `${receipt.durationMinutes} minutes` : 'Not available');

  doc.moveDown(1.4);
  const privacyBoxTop = doc.y;
  doc.roundedRect(54, privacyBoxTop, 486, 68, 8).fillAndStroke('#F6EFE8', palette.sand);
  doc.font('ShuraSans').fontSize(9).fillColor(palette.muted).text(
    'This receipt contains payment and appointment metadata only. It does not include therapy notes, intake responses, or message content.',
    70,
    privacyBoxTop + 17,
    { width: 454, lineGap: 3 }
  );

  doc.font('ShuraSans').fontSize(8).fillColor(palette.muted).text(
    'Generated by Shura from its durable payment record.',
    54,
    doc.page.height - 52,
    { width: 486, align: 'center' }
  );
  doc.end();
});

module.exports = { formatMoney, generateReceiptPdf };
